### ISSUE TITLE
Repater tabs lose color (but not style) when moved

### ISSUE THREAD

**Issue by aroly** [mdsecresearch/BurpSuiteSharpener#36]
Hi there,

I just noticed that if I apply a predefined pattern to a repeater tab, then move the tab, it loses its modified color (but not the custom font). 

Regards,

A.

**Comment by irsdl** [comment]
Thanks for reporting this bug. I had solved it when releasing the first version but it has been broken by applying more changes I think. I will try to fix it in the next version.
