### ISSUE TITLE
FR: Background colors

### ISSUE THREAD

**Issue by randomactsofsecurity** [mdsecresearch/BurpSuiteSharpener#44]
Rather than having icons for the main tabs (repeater, proxy etc) it would be cool if we could assign a custom background color to the tab so it's quicker to identify than icons (since the icons still have similar colors).

**Comment by a-marionette** [comment]
+1 But would also like the ability to apply to subtabs and still allow for an icon.

**Comment by irsdl** [comment]
I have seen this being implemented by extending the Java libraries; the only way to do this is by rewriting Burp Suite internal classes which are heavily obfuscated. Even if someone manages to do this, I think it will need an app reset and then the changes are gone. This is the same reason why I cannot change the tab colours in Repeater and Intruder tabs.

If you have an example of this being implemented in Burp somewhere I am happy to re-open it.
