### ISSUE TITLE
FR: Icons for Sub-tabs

### ISSUE THREAD

**Issue by a-marionette** [mdsecresearch/BurpSuiteSharpener#46]
Icons that are small enough to preserve the height of the sub-tabs would be another way to further help identify tabs of interest. For example, "Proxy, "HTTP History", etc could have smaller 16x16 icons (or similar).

**Comment by irsdl** [comment]
I should see how to resize the icons perhaps to give users choices of small - medium - large

**Comment by irsdl** [comment]
this has now been implemented
