### ISSUE TITLE
FR: Set tab icon sizes

### ISSUE THREAD

**Issue by CoreyD97** [mdsecresearch/BurpSuiteSharpener#58]
I love the tab icons, but would like the ability to shrink them down.
The implementation of a selectable size for the icons would be perfect. 

Thanks again for the plugin :)

**Comment by irsdl** [comment]
The next version will include this feature:
![image](https://user-images.githubusercontent.com/1798313/141297515-bd449f41-9db5-4b73-87ba-fda70dcbf1c7.png)

**Comment by irsdl** [comment]
This has been added now

**Comment by cocoonkid** [comment]
@irsdl came here to report that the icon size 8 and 6 are possibly buggy.  The difference between 10  and {8,6} is way to high.

They become nearly invisible.

![image](https://user-images.githubusercontent.com/43231640/191928455-e3429de4-4a10-407f-8ee0-feb006fe0182.png)

**Comment by irsdl** [comment]
Thanks for this, I had noticed this when implementing it but I think at the time I found out this is how Java Swing does handle this. Please feel free if you have found a solution I can use and I will fix it :)
