### ISSUE TITLE
FR: Vertical Repeater layouts

### ISSUE THREAD

**Issue by a-marionette** [mdsecresearch/BurpSuiteSharpener#68]
Hello,

I think an ideal layout for Burp Repeater would be to use a vertical style layout, similar to Inspector. The idea is the pane could be on either left or right side of the window. 

**Other features:**

- Default to VERB + URI for Tab Title
- Scrollable
- Compact, Comfortable row sizes
- Search and Filter by Request/Response body
- Sorting by A-Z, Last Modified, Originally Created, etc.

**Comment by irsdl** [comment]
These are all good features but require a lot of time. I had tried to implement the sorting or removal but this is not a thing in Java Swing especially as Burp is using customised JTabbedPane so I cannot remove/add them. However, as Burp Suite is going to totally change how its Repeater is going to look like, I think we shall wait and then implement anything that has not been addressed.

Regarding the filter or content dependent titles, I will need to find a way to get the request / response text which is very tricky without having a tab inside the editor (especially as editor can have 3 different views). I am thinking about these myself but I think I may go for implementing an IDE inside the editor first so then I can connect the tab to the contents that way.

**Comment by irsdl** [comment]
This will be added this year to Burp Suite by default so I am going to close this :)

**Comment by irsdl** [comment]
We were told in the Burp Suite Elders meeting that this feature had some problems and could not be released but they may reconsider if people ask for it.
