### ISSUE TITLE
MacOS error at startup

### ISSUE THREAD

**Issue by XTeam-Wing** [mdsecresearch/BurpSuiteSharpener#82]
Sharpener: The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by irsdl** [comment]
Unfortunately we were asked by PortSwigger to upgrade to the latest version so this is not going to be fixed. What's the issue with using the latest version of Java anyway? You can have multiple Java versions on your OS afaik.
However, another solution can be to build the project yourself using earlier Java versions (you will need to change a few lines of code as they only work with the latest Java).

**Comment by irsdl** [comment]
I think I have managed to do this using GitHub actions. You can download the compiled version for old version of Java from: https://github.com/mdsecresearch/BurpSuiteSharpener/actions/workflows/oldjdk-gradle.yml
e.g.: https://github.com/mdsecresearch/BurpSuiteSharpener/actions/runs/3018279088
