### ISSUE TITLE
screenshot option doesnt appear

### ISSUE THREAD

**Issue by mori1209** [mdsecresearch/BurpSuiteSharpener#86]
How can i take a screenshot of  intruder repeater tab? this option does not appear

**Comment by ShahafLevi** [comment]
?

**Comment by mori1209** [comment]
?

**Comment by irsdl** [comment]
I am not sure what your problem as you have provided minimal details. This option works for me in Intruder and in Repeater:

![image](https://user-images.githubusercontent.com/1798313/198411456-b24ecc47-2d16-47a3-8c62-06f6b4094155.png)

![image](https://user-images.githubusercontent.com/1798313/198411396-bfb8e9ab-a2ad-4ad3-95aa-897bf095e0c5.png)

**Comment by mori1209** [comment]
How did you open this window?

**Comment by mori1209** [comment]
I did it, thanks.
Can this be improved by taking a screenshot of the entire request?
The intention is that when the request is too large, we can take a screenshot that contains all its details
