### ISSUE TITLE
Sharpener never finishes loading

### ISSUE THREAD

**Issue by CrazyKidJack** [mdsecresearch/BurpSuiteSharpener#90]
__System Information__
- Burp Suite Version: 2023.1-18440 (Early Adopter)
  - however, I *think* I had the same problem on the previous version or two
- Sharpener version: 2.3 (locally installed)
  - however, I had the same problem with 2.1 (locally installed or through BApp store). When I first installed 2.1 it worked, but after a certain burp update (can't remember which one... i'm sorry... but it was relatively recent... definitely not further back than beginning of december... probably more recent) it stopped working
  
__Issue description__
When loading the extension, it never seems to finish loading.
In the output UI panel for the extension it only shows "Sharpener is being loaded...". In the past it eventually showed something like "Sharpener is up to date" but it does not show that now and none of the normal Sharpener UI changes are showing.

**Comment by irsdl** [comment]
I think this is similar to #89. If you hold the control key and click on the extension to reload it, does it fix itself at all?
Does this happen on a fresh project or something that had been loaded previously using another version of Sharpener perhaps?
I am beginning to think that there might be another extension causing the issue so could you please take the screenshot of extensions you have enabled as their order can also be important?
I also need to know the Java version and the OS please. I test it normally on Windows and I use its jar file and I use Java 17.

**Comment by CrazyKidJack** [comment]
I think I figured out the issue. With previous updates to the extension, I think it remembered all of my settings (including the auto-update setting which I had grown used to depending on to tell when it was finished loading).

However, with the update to 2.3. it seems it forgot that and other settings. So when I didn't see the custom icons nor the "is up to date" message in the extension output, I thought it was not loading. Just re-configuring seems to have done the trick.
